version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      args:
      - KEY_PATH=${KEY_PATH}
      - CERT_PATH=${CERT_PATH} 
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"   
    volumes:
      # - ./requirements/nginx/conf:/etc/nginx/conf.d/  
      - wp:/var/www/html 
    env_file:
      - .env   
    networks:
      - inception
    restart: on-failure 
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT=${DB_ROOT}
        - AD_USER=${AD_USER}
        - AD_PASS=${AD_PASS}
    image: mariadb
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql 
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    expose:
      - '9000'
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  wp:
    driver: local  
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb


